<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc1da54da32de88e242c1e0c22b61e681
{
    public static $prefixesPsr0 = array (
        'H' => 
        array (
            'HelpScout\\' => 
            array (
                0 => __DIR__ . '/..' . '/helpscout/api/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInitc1da54da32de88e242c1e0c22b61e681::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
